= Beyond the Basics: Operationalizing Red Hat OpenShift Virtualization

== Introduction
OpenShift Virtualization enables you to bring virtual machines onto a modern, Kubernetes-based infrastructure. It enables the development and delivery of new applications as well as the modernization of existing ones and can create applications that consist of virtual machines, containers, and serverless functions - all managed together using Kubernetes-native tools and paradigms.

== What content is covered in this lab?

* _OpenShift Virtualization Fundamentals_: In this section we will provide a review of virtual machine management fundamentals including: deployment, configuration, and live migration of resources.
* _Resource Management of Virtual Machines_: In this section we will cover adapting our virtual machines and clusters to meet increased workload demands including overcommitting CPU and memory, along with the hot modification of virtual resources.
* _Affinity and Dynamic Scheduling of Virtual Machines_: In this section we examine how we can control where virtual machines run for preferred performance and availability with considerations for workload balancing and the automatic placement of virtual machine by the OpenShift scheduler.
* _Fencing and Node Failure Remediation Scenarios_ In this section we show to to ensure workload resilience during potential infrastructure disruptions.
* _Multicluster Management of Virtual Machines_ In this section we examine a multi-cluster environment for virtual machines, and how to live migrate workloads between disparate clusters.

[[labenvironment]]
== Lab Environment

This lab is designed with an embedded Red Hat OpenShift console on the right side of the screen to conserve screen space for you as the user.

The following products and product versions are what constitute this lab environemnt.

* Red Hat OpenShift 4.21.9
* Red Hat OpenShift Virtualization 4.21.3
* Red Hat OpenShift Data Foundations 4.21.2
* Red Hat Advanced Cluster Management for Kubernetes 2.16
* Node Health Check Operator
* Self Node Remediation Operator
* Kube Descheduler Operator 5.3.2
* Migration Toolkit for Virtualization 2.11.3


[[labaccess]]
== Accessing the OpenShift Cluster

*Web Console*
{openshift_cluster_console_url}[{openshift_cluster_console_url},window=_blank]

*OpenShift Username*
[.wrap,console,role=execute,subs="attributes"]
----
{openshift_cluster_admin_username}
----

*OpenShift Password*
[.wrap,console,role=execute,subs="attributes"]
----
{openshift_cluster_admin_password}
----

*CLI Login*
[.wrap,console,role=execute,subs="attributes"]
----
oc login -u {openshift_cluster_admin_username} -p {openshift_cluster_admin_password} --server={openshift_api_server_url}
----
