= Beyond the Basics: Operationalizing Red Hat OpenShift Virtualization

== Introduction
OpenShift Virtualization enables you to bring virtual machines onto a modern, Kubernetes-based infrastructure. It enables the development and delivery of new applications as well as the modernization of existing ones and can create applications that consist of virtual machines, containers, and serverless functions - all managed together using Kubernetes-native tools and paradigms.

== What content is covered in this lab?

* _OpenShift Virtualization Fundamentals_: In this section we will provide a review of virtual machine management fundamentals including: deployment, configuration, and state management of virtual machines.
* _Live Migration of Virtual Workloads_: In this section we will demonstrate how virtual machines are able to live migrate between nodes as best determined by the Kubernetes scheduler, the end user, and show the live migration of virtual machines between storage classes.
* _Resource Management of Virtual Machines_: In this section we will cover adapting our virtual machines and clusters to meet increased workload demands including overcommitting CPU and memory. 
* _Hot-Plugging Virtual Machine Resources_: In this section we will walk through the process of adding additional resources to a running virtual machine. This will include CPU/Memory, an additonal virtual disk, and an additiona network adapter.
* _Affinity and Anti-Affinity for Virtual Machines_: In this section we examine how we can control where virtual machines run for preferred performance and availability with considerations for workload balancing.
* _Dynamic Scheduling of Virtual Workloads_: This section will cover how the OpenShift scheduler determines the placement of virtual machine resources, and how it balances workloads across the cluster.
* _Fencing and Node Failure Remediation Scenarios_ In this section we show to to ensure workload resilience during potential infrastructure disruptions.
* _Cross-Cluster Live Migration and Multicluster Scenarios_ In this section we examine a newer feature that allows for the live migration of virtual machines across clusters with an interactive pre-recorded demo.

[[labenvironment]]
== Lab Environment

This lab is designed with an embedded Red Hat OpenShift console on the right side of the screen to conserve screen space for you as the user.

The following products and product versions are what constitute this lab environemnt.

* Red Hat OpenShift 4.21.9
* Red Hat OpenShift Virtualization 4.21.3
* Red Hat OpenShift Data Foundation 4.21.2
* Node Health Check Operator 0.11.0
* Self Node Remediation Operator 0.12.1
* Kube Descheduler Operator 5.3.2
* Migration Toolkit for Virtualization 2.11.3


[[labaccess]]
== Accessing the OpenShift Cluster

Your OpenShift cluster console is available {openshift_cluster_console_url}[here^].

Your console login is available with:

* *User:* {openshift_cluster_admin_username}

* *Password:* {openshift_cluster_admin_password}


You can login to your OpenShift cluster on the provided terminal by copying and pasting the following syntax:

[source,sh,role=execute,subs="attributes"]
----
oc login -u {openshift_cluster_admin_username} -p {openshift_cluster_admin_password} --server={openshift_api_server_url}
----
